name: Deploy ComplexApps
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t temmix/complex-react-client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true temmix/complex-react-client npm test

      - name: Build images
        run: docker build -t temmix/complex-docker-client  ./client
          docker build -t temmix/complex-docker-nginx  ./nginx
          docker build -t temmix/complex-docker-server  ./server
          docker build -t temmix/complex-docker-worker  ./worker

      - name: Push images to docker Hub
        run: docker push temmix/complex-docker-client
          docker push temmix/complex-docker-nginx
          docker push temmix/complex-docker-server
          docker push temmix/complex-docker-worker
