name: Deploy ComplexApps
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t temmix/complex-react-client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true temmix/complex-react-client npm test

      - name: Build client image
        run: docker build -t temmix/complex-docker-client  ./client

      - name: Build nginx image
        run: docker build -t temmix/complex-docker-nginx  ./nginx

      - name: Build server image
        run: docker build -t temmix/complex-docker-server  ./server

      - name: Build worker image
        run: docker build -t temmix/complex-docker-worker  ./worker

      - name: Push temmix/complex-docker-client images to docker Hub
        run: docker push temmix/complex-docker-client

      - name: Push temmix/complex-docker-nginx images to docker Hub
        run: docker push temmix/complex-docker-nginx

      - name: Push temmix/complex-docker-server images to docker Hub
        run: docker push temmix/complex-docker-server

      - name: Push temmix/complex-docker-worker images to docker Hub
        run: docker push temmix/complex-docker-worker
